specVersion: 0.35.0
name: lambda-func
runtime: go
registry: docker.io/mexeniz
image: docker.io/mexeniz/kn-func-go:latest
imageDigest: ""
created: 2023-05-05T20:41:21.53300883+07:00
build:
  buildpacks:
  - paketo-buildpacks/go-dist
  - ghcr.io/boson-project/go-function-buildpack:tip
  builder: pack
  buildEnvs: []
run:
  volumes: []
  envs: []
deploy:
  namespace: ""
  remote: false
  annotations: {}
  options: {}
  labels: []
  healthEndpoints:
    liveness: /health/liveness
    readiness: /health/readiness
