specVersion: 0.35.0
name: lambda-func
runtime: python
registry: docker.io/munix
image: ""
imageDigest: ""
created: 2023-05-06T22:58:04.784987364+07:00
build: git                                          
git:
  url: https://github.com/mexeniz/mini-lambda.git   # required, git repository with the function source code
  revision: develop
  contextDir: k8s/lambda/lambda-func
run:
  volumes: []
  envs: []
deploy:
  namespace: "lambda"
  remote: false
  annotations: {}
  options: {}
  labels: []
  healthEndpoints:
    liveness: /health/liveness
    readiness: /health/readiness
