apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: simple-app
spec:
  template:
    spec:
      containers:
        - image: grc.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: "Go Sample v1"