apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: podinfo
  namespace: simple-app
spec:
  template:
    spec:
      containers:
        - image: stefanprodan/podinfo:6.3.6
          env:
            - name: PODINFO_UI_COLOR
              value: "#34577c"
          ports:
            - containerPort: 9898
