# Ref: https://knative.dev/docs/install/installing-istio/#using-istio-mtls-feature-with-knative
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: knative-serving
spec:
  mtls:
    mode: PERMISSIVE