apiVersion: apps/v1
kind: Deployment
metadata:
  name: ce-player
  labels:
    app: ce-player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ce-player
  template:
    metadata:
      labels:
        app: ce-player
    spec:
      containers:
      - name: main
        image: quay.io/ruben/cloudevents-player:v1.3
        env:
          # - name: BROKER_URI
          #   value: "http://broker-ingress.knative-eventing.svc.cluster.local:80"
          - name: BROKER_NAME
            value: "default"
          - name: BROKER_NAMESPACE
            value: "simple-app"
        ports:
        - containerPort: 8080