apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ce-viewer
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      containers:
        - image: n3wscott/sockeye:v0.6.3