apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: knative-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mexeniz/mini-lambda
    targetRevision: feat/knative-eventing-operator
    path: k8s/knative-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
