apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mexeniz/mini-lambda
    targetRevision: develop
    path: k8s/knative-serving
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
