apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: lambda
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mexeniz/mini-lambda
    targetRevision: main
    path: k8s/lambda
  destination:
    server: https://kubernetes.default.svc
    namespace: lambda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
