apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: simple-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mexeniz/mini-lambda
    targetRevision: main
    path: k8s/simple-app
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
