apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hellolambda
  namespace: simple-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "5"
    spec:
      containers:
        - image: jimmysong/knative-samples-helloworld-go:latest
          env:
            - name: TARGET
              value: "Mini Lambda v1"